# Example for displaying all images under docker.mclaneco.com repository in Nexus

# System representing the Nexus repository
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: nexus-repo
spec:
  owner: McLane

# Component representing the docker.mclaneco.com repository
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: docker-mclaneco-com-repository
  annotations:
    nexus-repository-manager/name: 'docker.mclaneco.com'
spec:
  type: repository
  lifecycle: production
  owner: McLane
